import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/app/app-shell";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export default async function PatientRecord({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const client = await createServerSupabaseClient();
  const { data: patient } = await client.schema("patients").from("records").select("id, full_name, registration_no, phone, dob, sex, created_at").eq("id", id).single();
  const { data: wounds } = await client.schema("clinical").from("wounds").select("id, wound_type, site, status, created_at").eq("patient_id", id).order("created_at", { ascending: false });
  const { data: orders } = await client.schema("treatment").from("orders").select("id, order_type, generic_name, dose, frequency, route, ordered_at").eq("patient_id", id).order("ordered_at", { ascending: false }).limit(10);
  const { data: labs } = await client.schema("investigations").from("lab_results").select("id, test_name, value_text, unit, test_date, verified_at").eq("patient_id", id).order("test_date", { ascending: false }).limit(10);
  const assessments = await Promise.all((wounds ?? []).map(async (wound) => { const { data } = await client.schema("clinical").from("wound_assessments").select("id, status, created_at").eq("wound_id", wound.id).order("created_at", { ascending: false }).limit(1).maybeSingle(); return [wound.id, data] as const; }));
  const latestAssessments = new Map(assessments);
  if (!patient) notFound();
  return <AppShell active="Patients"><div className="page-heading"><div><p className="eyebrow">Patient record · {patient.registration_no ?? "Registration"}</p><h1>{patient.full_name}</h1><p>{patient.sex ?? "Sex not recorded"} · {patient.phone ?? "No phone recorded"}</p></div><Link className="workspace-button" href={`/app/patients/${id}/wounds/new`}>+ New wound record</Link></div><div className="stat-grid"><div className="stat-card"><small>Date of birth</small><strong>{patient.dob ?? "—"}</strong><span>Identity record</span></div><div className="stat-card"><small>Registered</small><strong>{new Date(patient.created_at).toLocaleDateString()}</strong><span>Clinical record</span></div><div className="stat-card"><small>Wounds</small><strong>{wounds?.length ?? 0}</strong><span>Active clinical records</span></div></div><section className="panel"><div className="panel-title"><h2>Wounds</h2><span className="badge">Live record</span></div>{wounds?.length ? wounds.map((wound) => { const assessment = latestAssessments.get(wound.id); return <div className="patient-row" key={wound.id}><div className="patient-name">{wound.wound_type}<small>{wound.site ?? "Site not recorded"}</small></div><span>{wound.status}</span><span>{assessment?.status ?? "No assessment"}</span>{assessment ? <Link href={`/app/patients/${id}/wounds/${wound.id}/assessment/${assessment.id}`} style={{ color: "#2b8078", fontWeight: 700 }}>Review →</Link> : <Link href={`/app/patients/${id}/wounds/${wound.id}/assessment/new`} style={{ color: "#2b8078", fontWeight: 700 }}>Assess →</Link>}</div>; }) : <p>No wounds have been recorded yet.</p>}</section><section className="dashboard-grid"><div className="panel"><div className="panel-title"><h2>Treatment orders</h2><Link href={`/app/patients/${id}/orders/new`}>+ Add</Link></div>{orders?.length ? orders.map((order) => <p key={order.id}><strong>{order.generic_name}</strong> · {order.dose} · {order.frequency} · {order.route}</p>) : <p>No treatment orders recorded.</p>}</div><div className="panel"><div className="panel-title"><h2>Investigations</h2><Link href={`/app/patients/${id}/investigations/new`}>+ Add</Link></div>{labs?.length ? labs.map((lab) => <p key={lab.id}><strong>{lab.test_name}</strong> · {lab.value_text} {lab.unit} · {lab.verified_at ? "Verified" : "Awaiting verification"}</p>) : <p>No investigation results recorded.</p>}</div></section></AppShell>;
}
