"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { AppShell } from "@/app/app-shell";
import { createBrowserClient } from "@/lib/supabase/browser";

type Admission = { id: string; patient_id: string; location: string | null; admitted_at: string; status: string };
type Patient = { full_name: string; registration_no: string | null; sex: string | null; dob: string | null };
type Log = { id: string; log_date: string; nurse_payload: Record<string, string>; medical_officer_payload: Record<string, string>; consultant_payload: Record<string, string>; status: string };
type Note = { id: string; history_payload: Record<string, string>; examination_payload: Record<string, string>; safety_payload: Record<string, string>; status: string };
type Io = { id: string; direction: string; category: string; amount_ml: number; note: string | null };
type Order = { id: string; generic_name: string | null; dose: string | null; frequency: string | null; route: string | null };

const dhakaDate = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Dhaka" }).format(new Date());

export default function AdmissionDetail() {
  const { admissionId } = useParams<{ admissionId: string }>();
  const [admission, setAdmission] = useState<Admission | null>(null); const [patient, setPatient] = useState<Patient | null>(null); const [log, setLog] = useState<Log | null>(null); const [note, setNote] = useState<Note | null>(null); const [io, setIo] = useState<Io[]>([]); const [orders, setOrders] = useState<Order[]>([]);
  const [section, setSection] = useState("nurse"); const [noteText, setNoteText] = useState(""); const [pulse, setPulse] = useState(""); const [bp, setBp] = useState(""); const [spo2, setSpo2] = useState(""); const [temp, setTemp] = useState(""); const [message, setMessage] = useState("Loading admission chart..."); const [saving, setSaving] = useState(false);
  const [history, setHistory] = useState(""); const [exam, setExam] = useState(""); const [safety, setSafety] = useState(""); const [ioDirection, setIoDirection] = useState("input"); const [ioCategory, setIoCategory] = useState("feed"); const [ioAmount, setIoAmount] = useState(""); const [ioNote, setIoNote] = useState("");
  const [diagnosis, setDiagnosis] = useState(""); const [condition, setCondition] = useState(""); const [medRec, setMedRec] = useState(""); const [woundState, setWoundState] = useState(""); const [followUp, setFollowUp] = useState("");
  const [drug, setDrug] = useState(""); const [dose, setDose] = useState(""); const [frequency, setFrequency] = useState(""); const [route, setRoute] = useState(""); const [instructions, setInstructions] = useState(""); const [adminOrder, setAdminOrder] = useState(""); const [adminNote, setAdminNote] = useState("");

  async function load() { const client = createBrowserClient(); if (!client) { setMessage("Supabase is not configured."); return; } const a = await client.schema("clinical").from("ipd_admissions").select("id, patient_id, location, admitted_at, status").eq("id", admissionId).single(); if (a.error || !a.data) { setMessage(a.error?.message ?? "Admission not found."); return; } const [p, l, n, entries, orderResult] = await Promise.all([client.schema("patients").from("records").select("full_name, registration_no, sex, dob").eq("id", a.data.patient_id).single(), client.schema("clinical").from("ipd_daily_logs").select("id, log_date, nurse_payload, medical_officer_payload, consultant_payload, status").eq("admission_id", admissionId).eq("log_date", dhakaDate()).maybeSingle(), client.schema("clinical").from("ipd_admission_notes").select("id, history_payload, examination_payload, safety_payload, status").eq("admission_id", admissionId).maybeSingle(), client.schema("clinical").from("ipd_intake_output_entries").select("id, direction, category, amount_ml, note").eq("admission_id", admissionId).order("created_at", { ascending: false }).limit(20), client.schema("treatment").from("orders").select("id, generic_name, dose, frequency, route").eq("patient_id", a.data.patient_id).eq("order_type", "medication").order("ordered_at", { ascending: false }).limit(20)]); setAdmission(a.data); setPatient(p.data); setLog(l.data); setNote(n.data); setIo(entries.data ?? []); setOrders(orderResult.data ?? []); if (n.data) { setHistory(n.data.history_payload.history ?? ""); setExam(n.data.examination_payload.examination ?? ""); setSafety(n.data.safety_payload.safety ?? ""); } setMessage(a.error || p.error ? "Some chart data could not be loaded." : ""); }
  useEffect(() => { void load(); }, [admissionId]);

  async function saveDaily(event: FormEvent) { event.preventDefault(); setSaving(true); const client = createBrowserClient(); if (!client) return; const column = section === "nurse" ? "nurse_payload" : section === "medical_officer" ? "medical_officer_payload" : "consultant_payload"; const payload = section === "nurse" ? { pulse, blood_pressure: bp, spo2, temperature: temp, nursing_note: noteText } : section === "medical_officer" ? { complaints: noteText, assessment: noteText, plan: "Pending consultant review" } : { diagnosis: noteText, plan: noteText }; const result = log ? await client.schema("clinical").from("ipd_daily_logs").update({ [column]: payload }).eq("id", log.id).select("id, log_date, nurse_payload, medical_officer_payload, consultant_payload, status").single() : await client.schema("clinical").from("ipd_daily_logs").insert({ admission_id: admissionId, log_date: dhakaDate(), [column]: payload }).select("id, log_date, nurse_payload, medical_officer_payload, consultant_payload, status").single(); if (result.error) setMessage(result.error.message); else { setLog(result.data); setMessage("Daily entry saved."); } setSaving(false); }
  async function sign(role: string) { const client = createBrowserClient(); if (!client || !log) return; const { data: { user } } = await client.auth.getUser(); if (!user) { setMessage("Sign in is required."); return; } const reviewerRole = role === "nurse" ? "nurse" : role === "medical_officer" ? "medical_officer" : "consultant"; const result = await client.schema("clinical").from("ipd_reviews").upsert({ daily_log_id: log.id, reviewer_id: user.id, reviewer_role: reviewerRole }, { onConflict: "daily_log_id,reviewer_role" }); if (result.error) setMessage(result.error.message); else { if (reviewerRole === "consultant") await client.schema("clinical").from("ipd_daily_logs").update({ status: "locked" }).eq("id", log.id); setMessage(`${reviewerRole} section signed.`); await load(); } }
  async function saveAdmission(event: FormEvent) { event.preventDefault(); const client = createBrowserClient(); if (!client) return; const { data: { user } } = await client.auth.getUser(); if (!user) return setMessage("Sign in is required."); const result = note ? await client.schema("clinical").from("ipd_admission_notes").update({ history_payload: { history }, examination_payload: { examination: exam }, safety_payload: { safety }, updated_at: new Date().toISOString() }).eq("id", note.id) : await client.schema("clinical").from("ipd_admission_notes").insert({ admission_id: admissionId, history_payload: { history }, examination_payload: { examination: exam }, safety_payload: { safety }, created_by: user.id }); setMessage(result.error?.message ?? "Admission and safety screen saved."); await load(); }
  async function addIo(event: FormEvent) { event.preventDefault(); const client = createBrowserClient(); if (!client) return; const { data: { user } } = await client.auth.getUser(); if (!user || !ioAmount) return; const result = await client.schema("clinical").from("ipd_intake_output_entries").insert({ admission_id: admissionId, daily_log_id: log?.id ?? null, direction: ioDirection, category: ioCategory, amount_ml: Number(ioAmount), note: ioNote, recorded_by: user.id }); setMessage(result.error?.message ?? "Intake/output entry recorded."); setIoAmount(""); setIoNote(""); await load(); }
  async function addMedication(event: FormEvent) { event.preventDefault(); const client = createBrowserClient(); if (!client || !admission || !drug) return; const { data: { user } } = await client.auth.getUser(); if (!user) return; const result = await client.schema("treatment").from("orders").insert({ patient_id: admission.patient_id, encounter_id: null, order_type: "medication", generic_name: drug, dose, frequency, route, instructions, ordered_by: user.id }); setMessage(result.error?.message ?? "Medication order saved."); setDrug(""); setDose(""); setFrequency(""); setRoute(""); setInstructions(""); await load(); }
  async function administer(event: FormEvent) { event.preventDefault(); const client = createBrowserClient(); if (!client || !adminOrder) return; const { data: { user } } = await client.auth.getUser(); if (!user) return; const result = await client.schema("treatment").from("medication_administrations").insert({ order_id: adminOrder, administered_at: new Date().toISOString(), given_by: user.id, status: "given", note: adminNote }); setMessage(result.error?.message ?? "Medication administration recorded."); setAdminNote(""); }
  async function saveDischarge(signed = false) { const client = createBrowserClient(); if (!client) return; const { data: { user } } = await client.auth.getUser(); if (!user) return; const values = { admission_id: admissionId, diagnosis, condition_at_discharge: condition, medication_reconciliation: medRec, wound_state: woundState, follow_up_plan: followUp, status: signed ? "signed" : "draft", consultant_id: signed ? user.id : null, signed_at: signed ? new Date().toISOString() : null, created_by: user.id }; const result = await client.schema("clinical").from("ipd_discharge_summaries").upsert(values, { onConflict: "admission_id" }); setMessage(result.error?.message ?? (signed ? "Discharge summary signed." : "Discharge draft saved.")); }

  return <AppShell active="IPD admissions"><div className="page-heading"><div><p className="eyebrow">IPD clinical chart</p><h1>{patient?.full_name ?? "Admission chart"}</h1><p>{patient?.registration_no ?? "Registration pending"} · {admission?.location ?? "Location not recorded"}</p></div><Link className="text-link" href="/app/ipd/admissions">← Back to admissions</Link></div>{message && <p className="login-error">{message}</p>}{admission && <><div className="stat-grid"><div className="stat-card"><small>Admission</small><strong>{new Date(admission.admitted_at).toLocaleDateString()}</strong><span>{admission.status}</span></div><div className="stat-card"><small>Clinical date</small><strong>{dhakaDate()}</strong><span>Asia/Dhaka</span></div><div className="stat-card"><small>Daily chart</small><strong>{log?.status ?? "Not started"}</strong><span>{log ? "Signature workflow active" : "Open"}</span></div><div className="stat-card"><small>I/O balance</small><strong>{io.filter(x => x.direction === "input").reduce((a, x) => a + Number(x.amount_ml), 0) - io.filter(x => x.direction === "output").reduce((a, x) => a + Number(x.amount_ml), 0)} mL</strong><span>Recorded entries</span></div></div>
    <form className="panel form-panel" onSubmit={saveDaily}><p className="eyebrow">Daily progress and observations</p><div className="form-grid"><label>Section<select value={section} onChange={e => setSection(e.target.value)}><option value="nurse">Nurse observations</option><option value="medical_officer">Medical officer review</option><option value="consultant">Consultant review</option></select></label><label>Clinical note<textarea required value={noteText} onChange={e => setNoteText(e.target.value)} placeholder="Complaints, assessment, plan or nursing note" /></label>{section === "nurse" && <><label>Pulse<input value={pulse} onChange={e => setPulse(e.target.value)} /></label><label>Blood pressure<input value={bp} onChange={e => setBp(e.target.value)} placeholder="120/80" /></label><label>SpO2<input value={spo2} onChange={e => setSpo2(e.target.value)} /></label><label>Temperature<input value={temp} onChange={e => setTemp(e.target.value)} /></label></>}</div><button className="workspace-button" disabled={saving}>{saving ? "Saving..." : "Save daily entry"}</button>{log && <div className="button-row"><button type="button" className="text-link" onClick={() => void sign(section)}>Sign {section.replace("_", " ")} section</button></div>}</form>
    <form className="panel form-panel" onSubmit={saveAdmission}><p className="eyebrow">Admission / H&P and safety screen</p><div className="form-grid"><label>History and presenting complaint<textarea value={history} onChange={e => setHistory(e.target.value)} /></label><label>Examination findings<textarea value={exam} onChange={e => setExam(e.target.value)} /></label><label>Safety, allergies, risks and escalation plan<textarea value={safety} onChange={e => setSafety(e.target.value)} placeholder="Falls, pressure injury, allergy, infection or escalation risks" /></label></div><button className="workspace-button">Save H&P and safety screen</button></form>
    <form className="panel form-panel" onSubmit={addIo}><p className="eyebrow">Intake and output</p><div className="form-grid"><label>Direction<select value={ioDirection} onChange={e => setIoDirection(e.target.value)}><option value="input">Input</option><option value="output">Output</option></select></label><label>Category<select value={ioCategory} onChange={e => setIoCategory(e.target.value)}>{["feed","infusion","urine","stool","vomit","suction","drain","other"].map(x => <option key={x}>{x}</option>)}</select></label><label>Amount (mL)<input required type="number" min="1" value={ioAmount} onChange={e => setIoAmount(e.target.value)} /></label><label>Note<input value={ioNote} onChange={e => setIoNote(e.target.value)} /></label></div><button className="workspace-button">Record I/O</button>{io.length > 0 && <p>{io.slice(0, 5).map(x => `${x.direction}: ${x.category} ${x.amount_ml} mL`).join(" · ")}</p>}</form>
    <form className="panel form-panel" onSubmit={addMedication}><p className="eyebrow">Medication and treatment sheet</p><div className="form-grid"><label>Generic medication<input required value={drug} onChange={e => setDrug(e.target.value)} /></label><label>Dose<input required value={dose} onChange={e => setDose(e.target.value)} /></label><label>Frequency<input required value={frequency} onChange={e => setFrequency(e.target.value)} placeholder="e.g. 8 hourly" /></label><label>Route<input required value={route} onChange={e => setRoute(e.target.value)} placeholder="oral / IV / topical" /></label><label>Instructions<textarea value={instructions} onChange={e => setInstructions(e.target.value)} /></label></div><button className="workspace-button">Create medication order</button></form>
    {orders.length > 0 && <form className="panel form-panel" onSubmit={administer}><p className="eyebrow">Medication administration record</p><div className="form-grid"><label>Order<select required value={adminOrder} onChange={e => setAdminOrder(e.target.value)}><option value="">Select medication</option>{orders.map(o => <option key={o.id} value={o.id}>{o.generic_name} · {o.dose} · {o.route}</option>)}</select></label><label>Administration note<input value={adminNote} onChange={e => setAdminNote(e.target.value)} /></label></div><button className="workspace-button">Record dose given</button></form>}
    <form className="panel form-panel" onSubmit={e => { e.preventDefault(); void saveDischarge(false); }}><p className="eyebrow">Discharge summary</p><div className="form-grid"><label>Final diagnosis<textarea required value={diagnosis} onChange={e => setDiagnosis(e.target.value)} /></label><label>Condition at discharge<textarea value={condition} onChange={e => setCondition(e.target.value)} /></label><label>Medication reconciliation<textarea value={medRec} onChange={e => setMedRec(e.target.value)} /></label><label>Wound state<textarea value={woundState} onChange={e => setWoundState(e.target.value)} /></label><label>Follow-up plan<textarea value={followUp} onChange={e => setFollowUp(e.target.value)} /></label></div><div className="button-row"><button className="workspace-button">Save discharge draft</button><button type="button" className="text-link" onClick={() => void saveDischarge(true)}>Sign discharge summary</button></div></form>
  </>}</AppShell>;
}
