import { createBrowserClient } from "@/lib/supabase/browser";
import { canConfirmAssessment, canMarkWoundHealed } from "@/lib/clinical/governance";

async function session() { const client = createBrowserClient(); if (!client) return { client: null, user: null, profile: null }; const { data: { user } } = await client.auth.getUser(); if (!user) return { client, user: null, profile: null }; const { data: profile } = await client.schema("identity").from("staff_profiles").select("id, role, status").eq("id", user.id).single(); return { client, user, profile }; }

export async function confirmAssessment(assessmentId: string) {
  const { client, user, profile } = await session(); if (!client || !user) return { ok: false, message: "Sign in is required." }; if (!profile || profile.status !== "active" || !canConfirmAssessment(profile.role)) return { ok: false, message: "Only an active physician can confirm an assessment." };
  const now = new Date().toISOString(); const update = await client.schema("clinical").from("wound_assessments").update({ status: "physician_confirmed", consultant_confirmed_by: user.id, consultant_confirmed_at: now, confirmed_by: user.id, confirmed_at: now }).eq("id", assessmentId).eq("status", "draft"); if (update.error) return { ok: false, message: update.error.message };
  const signature = await client.schema("clinical").from("clinical_signatures").insert({ assessment_id: assessmentId, signer_id: user.id, signer_role: "physician", signature_type: "consultant_confirmation" }); if (signature.error) return { ok: false, message: signature.error.message }; return { ok: true, message: "Assessment confirmed and signed." };
}

export async function requestAssessmentCorrection(assessmentId: string, reason: string) { const { client, user } = await session(); if (!client || !user) return { ok: false, message: "Sign in is required." }; if (reason.trim().length < 5) return { ok: false, message: "Enter a meaningful correction reason." }; const result = await client.schema("clinical").from("correction_requests").insert({ assessment_id: assessmentId, requested_by: user.id, assigned_to: user.id, reason: reason.trim() }); return { ok: !result.error, message: result.error?.message ?? "Correction request submitted." }; }

export async function createAssessmentAmendment(assessmentId: string, payload: Record<string, unknown>, reason: string) { const { client, user, profile } = await session(); if (!client || !user) return { ok: false, message: "Sign in is required." }; if (!profile || profile.status !== "active" || !canConfirmAssessment(profile.role)) return { ok: false, message: "Only an active physician can approve an amendment." }; if (reason.trim().length < 5) return { ok: false, message: "Enter a meaningful amendment reason." }; const latest = await client.schema("clinical").from("wound_assessment_versions").select("version_number").eq("assessment_id", assessmentId).order("version_number", { ascending: false }).limit(1).maybeSingle(); const version = (latest.data?.version_number ?? 0) + 1; const inserted = await client.schema("clinical").from("wound_assessment_versions").insert({ assessment_id: assessmentId, version_number: version, payload, created_by: user.id, correction_reason: reason.trim() }); if (inserted.error) return { ok: false, message: inserted.error.message }; const updated = await client.schema("clinical").from("wound_assessments").update({ payload, amendment_reason: reason.trim() }).eq("id", assessmentId); return { ok: !updated.error, message: updated.error?.message ?? `Amendment version ${version} created.` }; }

export async function markWoundHealed(woundId: string) { const { client, user, profile } = await session(); if (!client || !user) return { ok: false, message: "Sign in is required." }; if (!profile || profile.status !== "active" || !canMarkWoundHealed(profile.role)) return { ok: false, message: "Only an active physician can mark a wound healed." }; const now = new Date().toISOString(); const result = await client.schema("clinical").from("wounds").update({ status: "healed" }).eq("id", woundId).eq("status", "active"); if (result.error) return { ok: false, message: result.error.message }; const signature = await client.schema("clinical").from("clinical_signatures").insert({ signer_id: user.id, signature_type: "healed_confirmation", signer_role: "physician", signed_at: now }); return { ok: !signature.error, message: signature.error?.message ?? "Wound marked healed." }; }

export async function resolveCorrectionRequest(requestId: string, resolution: "resolved" | "rejected") { const { client, user, profile } = await session(); if (!client || !user) return { ok: false, message: "Sign in is required." }; if (!profile || profile.status !== "active" || !canConfirmAssessment(profile.role)) return { ok: false, message: "Only an active physician can resolve a correction request." }; const result = await client.schema("clinical").from("correction_requests").update({ status: resolution, resolved_at: new Date().toISOString(), resolved_by: user.id }).eq("id", requestId); return { ok: !result.error, message: result.error?.message ?? `Correction request ${resolution}.` }; }

export async function reopenWound(patientId: string, woundId: string, reason: string) { const { client, user, profile } = await session(); if (!client || !user) return { ok: false, message: "Sign in is required." }; if (!profile || profile.status !== "active") return { ok: false, message: "Active staff membership is required." }; if (reason.trim().length < 5) return { ok: false, message: "Enter a reopening reason." }; const original = await client.schema("clinical").from("wounds").select("wound_type, site").eq("id", woundId).single(); if (!original.data) return { ok: false, message: "Original wound was not found." }; const result = await client.schema("clinical").from("wounds").insert({ patient_id: patientId, wound_type: original.data.wound_type, site: original.data.site, first_noted_date: new Date().toISOString().slice(0, 10), status: "active" }).select("id").single(); if (result.error || !result.data) return { ok: false, message: result.error?.message ?? "Reopened wound could not be created." }; return { ok: true, woundId: result.data.id, message: "Reopened wound created as a new clinical record." }; }
