import Link from "next/link";
/* eslint-disable @next/next/no-img-element */
import { notFound } from "next/navigation";
import { AppShell } from "@/app/app-shell";
import { AssessmentReview } from "./review";
import { CorrectionActions } from "./correction-actions";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export default async function AssessmentPage({ params }: { params: Promise<{ id: string; woundId: string; assessmentId: string }> }) {
  const { id, woundId, assessmentId } = await params; const client = await createServerSupabaseClient();
  const { data: assessment } = await client.schema("clinical").from("wound_assessments").select("id, wound_id, length_cm, width_cm, depth_cm, area_cm2, payload, status, created_at").eq("id", assessmentId).eq("wound_id", woundId).single(); if (!assessment) notFound();
  const { data: photos } = await client.schema("clinical").from("wound_photos").select("id, storage_path").eq("wound_assessment_id", assessmentId);
  const { data: versions } = await client.schema("clinical").from("wound_assessment_versions").select("id, version_number, correction_reason, created_at").eq("assessment_id", assessmentId).order("version_number", { ascending: false });
  const { data: corrections } = await client.schema("clinical").from("correction_requests").select("id, reason, status, created_at").eq("assessment_id", assessmentId).order("created_at", { ascending: false });
  const signedPhotos = await Promise.all((photos ?? []).map(async (photo) => { const result = await client.storage.from("wound-photos").createSignedUrl(photo.storage_path, 900); return { ...photo, url: result.data?.signedUrl ?? null }; }));
  return <AppShell active="Patients"><div className="page-heading"><div><p className="eyebrow">Assessment review</p><h1>Wound assessment</h1><p>Review the clinical entry before confirmation.</p></div><Link className="text-link" href={`/app/patients/${id}`}>← Back to patient</Link></div><section className="panel"><div className="stat-grid"><div className="stat-card"><small>Length</small><strong>{assessment.length_cm} cm</strong></div><div className="stat-card"><small>Width</small><strong>{assessment.width_cm} cm</strong></div><div className="stat-card"><small>Depth</small><strong>{assessment.depth_cm} cm</strong></div><div className="stat-card"><small>Area</small><strong>{assessment.area_cm2 ?? "—"} cm²</strong></div></div><p>{(assessment.payload as { note?: string })?.note || "No clinical note recorded."}</p><p><span className="badge">{assessment.status}</span> · {photos?.length ?? 0} photo(s)</p>{signedPhotos.length > 0 && <div className="dashboard-grid">{signedPhotos.map((photo) => photo.url ? <img key={photo.id} src={photo.url} alt="Wound clinical photo" style={{ width: "100%", borderRadius: 8 }} /> : <p key={photo.id}>Photo preview unavailable.</p>)}</div>}<div className="panel-title"><h2>Assessment history</h2></div>{versions?.length ? versions.map((version) => <p key={version.id}>Version {version.version_number} · {new Date(version.created_at).toLocaleString()} {version.correction_reason ? `· ${version.correction_reason}` : ""}</p>) : <p>No amendments recorded.</p>}<div className="panel-title"><h2>Correction requests</h2></div>{corrections?.length ? corrections.map((request) => <p key={request.id}><span className="badge">{request.status}</span> · {request.reason} {request.status === "open" && <CorrectionActions requestId={request.id} status={request.status} />}</p>) : <p>No correction requests.</p>}<AssessmentReview assessmentId={assessment.id} patientId={id} woundId={woundId} status={assessment.status} initialPayload={{ length: assessment.length_cm, width: assessment.width_cm, depth: assessment.depth_cm, note: (assessment.payload as { note?: string })?.note ?? "" }} /></section></AppShell>;
}
