"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { AppShell } from "@/app/app-shell";
import { createBrowserClient } from "@/lib/supabase/browser";
const types = ["Diabetic Foot", "Vascular Wound", "Burn", "Post-Infective", "Pressure Injury", "Traumatic", "Surgical", "Other"];
export default function NewPatientWound() { const { id } = useParams<{ id: string }>(); const router = useRouter(); const [type, setType] = useState(types[0]); const [site, setSite] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const client = createBrowserClient(); if (!client) { setMessage("Supabase is not configured."); setSaving(false); return; } const { data: { user } } = await client.auth.getUser(); if (!user) { setMessage("Sign in is required."); setSaving(false); return; } const membership = await client.schema("identity").from("staff_clinic_memberships").select("clinic_id").eq("staff_id", user.id).limit(1).single(); if (!membership.data) { setMessage("No clinic membership found."); setSaving(false); return; } const visit = await client.schema("clinical").from("opd_visits").insert({ patient_id: id, clinic_id: membership.data.clinic_id, created_by: user.id, visit_reason: "Initial wound assessment" }).select("id").single(); if (visit.error || !visit.data) { setMessage(visit.error?.message ?? "OPD visit could not be created."); setSaving(false); return; } const wound = await client.schema("clinical").from("wounds").insert({ patient_id: id, wound_type: type, site, first_noted_date: new Date().toISOString().slice(0, 10) }).select("id").single(); if (wound.error || !wound.data) { setMessage(wound.error?.message ?? "Wound could not be created."); setSaving(false); return; } router.push(`/app/patients/${id}`); }
  return <AppShell active="Patients"><div className="page-heading"><div><p className="eyebrow">New wound record</p><h1>Start wound documentation</h1><p>Create the wound and OPD visit before recording measurements and photos.</p></div><Link className="text-link" href={`/app/patients/${id}`}>← Back to patient</Link></div><form className="panel form-panel" onSubmit={submit}><p className="eyebrow">Wound classification</p><div className="type-picker">{types.map((item) => <button type="button" className={item === type ? "selected" : ""} onClick={() => setType(item)} key={item}>{item}</button>)}</div><div className="form-grid"><label>Anatomical site<input required placeholder="e.g. right plantar foot" value={site} onChange={(event) => setSite(event.target.value)} /></label></div>{message && <p className="login-error">{message}</p>}<div className="form-actions"><Link className="text-link" href={`/app/patients/${id}`}>Cancel</Link><button className="workspace-button" disabled={saving}>{saving ? "Creating…" : "Create wound →"}</button></div></form></AppShell>; }
