create table if not exists clinical.ipd_admissions (id uuid primary key default gen_random_uuid(), patient_id uuid not null references patients.records(id) on delete restrict, clinic_id uuid not null references identity.clinics(id), admitted_at timestamptz not null default now(), discharged_at timestamptz, location text, status text not null default 'active' check (status in ('active','discharged','cancelled')), admitted_by uuid not null references identity.staff_profiles(id));
create table if not exists clinical.ipd_daily_logs (id uuid primary key default gen_random_uuid(), admission_id uuid not null references clinical.ipd_admissions(id) on delete restrict, log_date date not null, is_partial boolean not null default false, nurse_payload jsonb not null default '{}', medical_officer_payload jsonb not null default '{}', consultant_payload jsonb not null default '{}', status text not null default 'open' check (status in ('open','review','locked')), created_at timestamptz not null default now(), unique(admission_id, log_date));
create table if not exists clinical.ipd_entry_schedules (id uuid primary key default gen_random_uuid(), daily_log_id uuid not null references clinical.ipd_daily_logs(id) on delete cascade, section text not null, frequency text not null, next_due_at timestamptz, missed_reason text, status text not null default 'pending' check (status in ('pending','completed','missed','overdue')));
create table if not exists clinical.ipd_reviews (id uuid primary key default gen_random_uuid(), daily_log_id uuid not null references clinical.ipd_daily_logs(id) on delete cascade, reviewer_id uuid not null references identity.staff_profiles(id), reviewer_role identity.user_role not null, reviewed_at timestamptz not null default now(), signature_path text, unique(daily_log_id, reviewer_role));
alter table clinical.ipd_admissions enable row level security; alter table clinical.ipd_daily_logs enable row level security; alter table clinical.ipd_entry_schedules enable row level security; alter table clinical.ipd_reviews enable row level security;
create policy ipd_admission_access on clinical.ipd_admissions for all to authenticated using (identity.can_access_patient(patient_id)) with check (identity.can_access_patient(patient_id));
create policy ipd_log_access on clinical.ipd_daily_logs for all to authenticated using (exists(select 1 from clinical.ipd_admissions a where a.id=admission_id and identity.can_access_patient(a.patient_id))) with check (identity.is_active_staff());
create policy ipd_schedule_access on clinical.ipd_entry_schedules for all to authenticated using (exists(select 1 from clinical.ipd_daily_logs l join clinical.ipd_admissions a on a.id=l.admission_id where l.id=daily_log_id and identity.can_access_patient(a.patient_id))) with check (identity.is_active_staff());
create policy ipd_review_access on clinical.ipd_reviews for all to authenticated using (exists(select 1 from clinical.ipd_daily_logs l join clinical.ipd_admissions a on a.id=l.admission_id where l.id=daily_log_id and identity.can_access_patient(a.patient_id))) with check (reviewer_id=auth.uid() and identity.is_active_staff());
